### ISSUE TITLE
Is it possible to use it on windows Service?

### ISSUE THREAD

**Issue by sharmarohit0013** [OpenCppCoverage/OpenCppCoverage#91] opened 2019-06-13 08:29 UTC
## Describe your environment
- Version of OpenCppCoverage: 0.9.7.0
- Architecture (x86/ x64): x64
- Windows version: 10

## Describe your problem
Steps to reproduce:
1. create a windows service
2. execute openCppCoverage on this service.exe (service in an multi-threaded application)

## Observation_
1. after running $>OpenCppCoverage C:\MyProject\service.exe 
within few minutes it get crash.
2. report is generated with only part of service.exe code cover.

Is it possible to use it on windows Service? 
if yes then how?
if no then are there any plan for future?

**Comment by OpenCppCoverage** [comment] 2019-06-18 10:57
Hello,

Yes it is possible to use OpenCppCoverage on a Windows service.
I have just added a new entry into the [FAQ](https://github.com/OpenCppCoverage/OpenCppCoverage/wiki/FAQ#windows-service-support).

I need more information about what your service does.
Can you upload the source code of your service? 
If not, can you reproduce the issue on a toy example?

OpenCppCoverage

**Comment by sharmarohit0013** [comment] 2019-06-19 10:14
Thanks,
i am already using the workaround(passing arg to run as console application) mention in FAQ.

**Can you upload the source code of your service?**
sorry i cant.

**If not, can you reproduce the issue on a toy example?**
sorry, to create this will take some time. if i am able to do it then will share it with you.

**Comment by OpenCppCoverage** [comment] 2019-06-20 12:59
Do you have the issue with if you run:
```
OpenCppCoverage --excluded_modules=* C:\MyProject\service.exe
```

**Comment by sharmarohit0013** [comment] 2019-06-21 07:42
doesn't works
result
****
*
*
[debug] Module: C:\Windows\System32\nsi.dll is not selected because it matches excluded pattern: *
[debug] Module: C:\Windows\System32\icmp.dll is not selected because it matches excluded pattern: *
[debug] Module: C:\Windows\System32\icmp.dll is not selected because it matches excluded pattern: *
[debug] Module: C:\Windows\System32\umppc8603.dll is not selected because it matches excluded pattern: *
[debug] Module: C:\Windows\System32\umppc8603.dll is not selected because it matches excluded pattern: *
[debug] Module: C:\Windows\System32\kernel.appcore.dll is not selected because it matches excluded pattern: *
[debug] Exit thread:18248
[debug] Exit thread:26028
[debug] Exit thread:23732
[debug] Exit thread:7528
[debug] Exit thread:15072
[debug] Exit Process:15880
[info] ----------------------------------------------------
[info] Coverage generated in Folder C:\WINDOWS\system32\CoverageReport-2019-06-21-13h09m41s
[info] ----------------------------------------------------
[warning] No modules were selected. Please check the values of --modules and --excluded_modules.
You can try to remove all --modules and --excluded_modules and use --modules=C:\MyProject instead.
****

**Comment by OpenCppCoverage** [comment] 2019-06-21 09:21
Hello,

The previous command was not supposed to solve the issue. The goal of the test was to know if your program crashes because it was run under a debugger (OpenCppCoverage acts as a debugger) or because OpenCppCoverage updates the memory of your program in an incorrectly way. It looks like it is the second option.

The issue can happen when running optimized build (release build) without flag ``--optimized_build``. Is that your case?

If not, it means your program has something special that OpenCppCoverage cannot handle and I need a way to reproduce it.
To find out which part of the code has an issue, you can try running your program with different values of 
``--modules`` and then with different values of ``--sources``. In this way you can locate the problematic file and find an way to reproduce the issue. 

Let me know if you have any questions,

OpenCppCoverage

**Comment by mengfei227** [comment] 2019-11-08 02:49
想问一个问题，我在powershell中使用OpenCppCoverage.exe 运行这样的.\OpenCppCoverage.exe --sources D:\software\gitlab-runner\builds\8960b6c5\0\mengfei.wang\windows-test --modules=D:\software\gitlab-runner\builds\8960b6c5\0\mengfei.wang\windows-test D:\software\gitlab-runner\builds\8960b6c5\0\mengfei.wang\windows-test\test.exe  
依然提示我No modules were selected. Please check the values of --modules and --excluded_modules.
You can try to remove all --modules and --excluded_modules and use --modules=D:\software\gitlab-runner\builds\8960b6c5\0\mengfei.wang\windows-test instead 是什么意思？

**Comment by OpenCppCoverage** [comment] 2020-05-02 09:32
Hi,

@sharmarohit0013: I am closing this issue as I cannot make any progress without additional information. Feel free to reopen this issue if you have a step to reproduce the problem.

@mengfei227 : Did you check https://github.com/OpenCppCoverage/OpenCppCoverage/wiki/FAQ#coverage-report-is-empty?

OpenCppCoverage

**Closed by OpenCppCoverage** 2020-05-02 09:32 UTC
Labels: Need feedbacks
